### PR TITLE
Initial implementation of applet and host

### PR DESCRIPTION
**Pull request by Nomit1993**

### CODE REVIEW

**Comment by mgrabovsky** [comment]
Hi, thanks for taking this up! I see several problems, though. First of all, the code does not compile. There's seems to be some misplaced code in the applet class.

Secondly, there are a lot of unused variables (`baTempA`, `baTempB`, ...). I mean they're used inside `processINSD1`, but not after that, so I would get rid of them now. I would prefer to keep the changes at absolute minimum necessary, i.e. only add code or documentation that will be used later on and it's absolutely clear where its place is.

Thirdly, there are almost no comments in the code. Since we need to cooperate on this project, I think a little bit more explanation of what's going on in the code would be helpful. It is therefore unclear what the purpose of the files `SimpleAPDU.java`, `CardMngr.java` and `ISO7816_status_words.txt` is. They're not used anywhere in the remaining code.

Lastly, the `CardMngr.java` file mentions that the author is xsvenda. Is this code from one of the seminars? I think we're only allowed to use our own code in the project.

Also, the commit history is somewhat unreadable. There are two useless commits ("Create n", "Delete n") and the commit messages are not very helpful – "Add files via upload" and "Update PV204Applet.java" don't tell us much about the contents of the commit.

If you need some tips, Linus Torvalds [wrote a short, handy guide](https://github.com/torvalds/subsurface-for-dirk/blob/a48494d2fbed58c751e9b7e8fbff88582f9b2d02/README#L88-L115) on how to write good commit messages.

We're also going to need a `build.xml` file for ant.

**Comment by Nomit1993** [comment]
Hello Matej,

Thank you for looking into the code.
1. About the code compilation issue, i am attaching the complete project as
a zip file. Let me know if you now face any issues.
2. About the unused variables, i will be using them once i start working on
implementation of speke which i am hopeful to complete by 16.04.2020.
3. About the comments, i will surely be commenting each and every part of
the code for ease of understanding. The ISO7816_status_words.txt is for the
reference in case of any errors in the code during the execution.
4. Regarding CardMngr.java, i will write to Svenda asking him about his
permission or negation about using his java code, though, like you said, we
can write our own too.
5. About the commit 'Create n and Delete n', i will remove them.
6. Matej, i have not used GitHub much and i thank you for sending me the
link of 'handy guide' which i will definitely look into.
7. My main aim was to get the idea from you guys and you have been quite
helpful in this regards.
8. Matej, i am attaching the zip file containing the project as has been
executed in my machine. I wish you to let me know whether we are going in
right direction wrt code per se or not.
9. As said in point number 2, i will start speke implementation tomorrow.
Let me know if you have any points.
10. The thing is that my laptop got corrupted but now it is doing good so i
could not able to work on the project today.
11. Any suggestions, let me know.

https://drive.google.com/open?id=139t0r47hgS13OppzKVQxCtMjv7Xf4cQl

Thank you.

**Comment by mgrabovsky** [comment]
Hi Nomit, I'll take a better look at the code tomorrow as I'm extremely busy right now.

**Comment by Nomit1993** [comment]
Hey Matej,

I was hopeful that i would receive some kind of reply from you.

Anyways, if you do have any observation or suggestions, kindly let me know.
I am planning to implement SPEKE tomorrow.

To be brief, till now, ecdh parameters on both the sides have been
generated. For generation of shared secret, i will use the SPEKE formula.
Once both users have a common shared secret, then they can start the
communication by sending message using some encryption method (aes etc.)
using the PIN.

Since for submission of phase 2, few days are left, kindly let me know your
observations.

Thank you.

**Comment by mgrabovsky** [comment]
Hi, I'm deeply sorry for the delays. I hope to recheck the code later today and move on with one of the remaining tasks.

**Comment by Nomit1993** [comment]
Ok. I am sharing you the link of the latest modified zip file.

To be brief, till now, ecdh parameters on both the sides have been
generated. For generation of shared secret, i will use the SPEKE formula.
Once both users have a common shared secret, then they can start the
communication by sending message using some encryption method (aes etc.)
using the PIN.

https://drive.google.com/open?id=1E6QHC2IiZKTsELdzTFRAvV1i3uAr6Jem

**Comment by mgrabovsky** [comment]
I just checked the latest ZIP file and the code looks OK.

Can you please add all the code, build and project files into this pull request? That is, all the files in the `src` and `nbproject` directories and also the `build.xml` file.

**Comment by mgrabovsky** [comment]
I also changed the title of the pull request to "Initial implementation of applet and host" so that it's clear what part of the project it's dealing with.

**Comment by mgrabovsky** [comment]
I'm merging this for now. Will deal with improvements in later commits.

**Pull request merged**
